### PR TITLE
Adding docker

### PR DESCRIPTION
**Pull request by pryorda**
#174 was inadvertently closed and  the conversation from there should move here I guys.

### CODE REVIEW

**Comment by pryorda** [comment]
Labels need added: enhancement, server, agent?

**Comment by 0xdade** [comment]
In the future I think the preferred approach to this is to reopen the previous pull request if at all possible to avoid duplicates.

**Comment by 0xdade** [comment]
Also, prior to this getting accepted, I'll need you to include documentation about running the respective components with docker. Please update the `natlas-server/README.md` and `natlas-agent/README.md` files with a new subsection called Docker that explains how to setup and use this capability.

**Comment by pryorda** [comment]
I tried to reassign the branch but it wouldn't let me, but I def agree.

**Comment by ajacques** [comment]
Docker-compose is generally more useful for development environments instead of production environments. To be useful for development, we'd need to mount the cwd into Docker and configure Django run environments.

Is the goal to have a consistent development or end-user story or both? I'd likely recommend a Helm or cloud-provider infra as code strategy for deploying this if we're targeting this for use by end users, but it depends on exactly what our end-user deployment strategy is.

As written, these Docker images are going to be inefficient from a end-user vending perspective as every version bump will be a full image replacement. This is because all of the dependencies are installed in the `setup-*.py` scripts and build kit won't be able to cache a layer with the dependencies.

@0xdade, we can go in multiple directions here.

**Comment by 0xdade** [comment]
I think, for me, the primary focus for Dockerfiles / containerizing is to ease end-user deployment. An end user deployment would typically be broken down roughly like this.

architecture

This diagram was created back in April and it doesn't necessarily match exactly how containers would be used to deploy. But the gist of it is that as a user, I would deploy one server somewhere and connect it to an elasticsearch cluster, configure everything (which is stored persistently in metadata.db, but the database path can be changed by modifying the environment as noted in `natlas-server/config.py`):

https://github.com/natlas/natlas/blob/41e56084c195d30cd12d114330a488558de37b39/natlas-server/config.py#L20-L21

Once the server is stood up, there may be one or more remotely deployed agents that connect over http(s) to the server. The agents need to be configurable with everything available in https://github.com/natlas/natlas/blob/41e56084c195d30cd12d114330a488558de37b39/natlas-agent/config.py. 

It sounds like the recommendation to make the containerizing more efficient is to use the Dockerfile itself to setup/install dependencies separately from the `setup-*.sh` scripts that might be used in non-dockerized deployments. My only concern then is managing system dependencies in multiple places in order to support both deployment models.

Maybe let's hop on a call tomorrow or something and discuss this further?

**Comment by pryorda** [comment]
Lets def jump on a call/meeting to discuss this. There are topics being obfuscated here for sure.

How do you want to meet?

**Comment by 0xdade** [comment]
I've mocked up some information about deployment scenarios on [a wiki page](https://github.com/natlas/natlas/wiki/Deployment-Scenarios). I should probably set up a place that conversations can be had and discussions organized. But right now I don't have that.

**Comment by 0xdade** [comment]
@pryorda I think we're going to go the route of #190. The way the Dockerfiles are structured will enable easier builds and handles a number of things that we hadn't really thought about already, with minimal code changes at the expense of it being a separate place to manage new dependencies.

I appreciate the work you put into bringing natlas to docker, without this PR we would have never actually gotten the ball moving. I hope to see your future contributions.

**Pull request closed without merging**
